#!/usr/bin/env bash
# Mac 用 .app バンドルを生成する（ダブルクリックでターミナル無しに起動できる）。
#
#   ./launcher/build_mac_app.sh              → ./Creator DNA Editor.app
#   ./launcher/build_mac_app.sh /path/to/dir → そのフォルダの中に生成
#
# 中身は「launcher/creator_dna_editor.py を python3 で呼ぶだけ」の薄いシェル。
# 署名・公証はしない（ローカルで生成した .app は quarantine 属性が付かないのでそのまま開ける。
# 他の Mac に配る場合は右クリック→開く、が必要）。
# リポジトリを移動したら作り直す（絶対パスも埋め込んでいるので、.app を Dock や Applications に置いても動く）。
set -euo pipefail

REPO="$(cd "$(dirname "$0")/.." && pwd)"
DEST_DIR="${1:-$REPO}"
APP_NAME="Creator DNA Editor"
APP="$DEST_DIR/$APP_NAME.app"
LAUNCHER_REL="launcher/creator_dna_editor.py"

rm -rf "$APP"
mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources"

# --- 実行体: リポジトリ直下に置かれていれば相対パス、そうでなければビルド時の絶対パスで探す ---
cat > "$APP/Contents/MacOS/launch" <<EOF
#!/bin/bash
# $APP_NAME — generated by launcher/build_mac_app.sh. 実体は $LAUNCHER_REL
HERE="\$(cd "\$(dirname "\$0")" && pwd)"
SCRIPT="\$HERE/../../../$LAUNCHER_REL"
if [ ! -f "\$SCRIPT" ]; then
  SCRIPT="$REPO/$LAUNCHER_REL"
fi
if [ ! -f "\$SCRIPT" ]; then
  /usr/bin/osascript -e 'display dialog "リポジトリが見つかりません。launcher/build_mac_app.sh を実行して .app を作り直してください。" with title "$APP_NAME" buttons {"OK"} with icon stop' >/dev/null 2>&1 || true
  exit 1
fi
exec /usr/bin/env python3 "\$SCRIPT"
EOF
chmod +x "$APP/Contents/MacOS/launch"

# --- Info.plist ---
cat > "$APP/Contents/Info.plist" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleName</key>
	<string>$APP_NAME</string>
	<key>CFBundleDisplayName</key>
	<string>$APP_NAME</string>
	<key>CFBundleIdentifier</key>
	<string>local.creator-dna-editor.launcher</string>
	<key>CFBundleExecutable</key>
	<string>launch</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleVersion</key>
	<string>1</string>
	<key>CFBundleShortVersionString</key>
	<string>0.1</string>
	<key>LSMinimumSystemVersion</key>
	<string>12.0</string>
	<key>LSUIElement</key>
	<false/>
	<key>NSHighResolutionCapable</key>
	<true/>
</dict>
</plist>
EOF

printf 'APPL????' > "$APP/Contents/PkgInfo"

echo "生成しました: $APP"
echo "Finder でダブルクリックすると起動します（初回は依存インストールで数分。進捗は data/launcher.log）。"
